### ISSUE TITLE
No callback provided to pbkdf2 - 32 bit node

### ISSUE THREAD

**Issue by WhiteAbeLincoln** [joyent/node#13859]
Using the 32 bit node binary (both windows and linux), pbkdf2 throws an error `[Error: No callback provided to pbkdf2]`. This does not occur when using the 64 bit distribution. Tested with the example from the node.js docs

```javascript
crypto.pbkdf2('secret', 'salt', 4096, 512, 'sha256', function(err, key) {
  if (err)
    throw err;
  console.log(key.toString('hex'));  // 'c5e478d...1469e50'
});
```

**Comment by CGavrila** [comment]
What version(s) are you using? That function changed its signature from 
```
crypto.pbkdf2(password, salt, iterations, keylen, callback) 
```
in v0.10 to 
```
crypto.pbkdf2(password, salt, iterations, keylen[, digest], callback)
```
in v0.12.

**Comment by WhiteAbeLincoln** [comment]
That might be it. I will update node on my 32 bit server and check.

**Comment by misterdjules** [comment]
As indicated by @CGavrila, the code mentioned in this issue's description throws with v0.10 but not with v0.12 because the signature of this function has changed.

Closing as it seems to be working as expected, please let me know if it's still an issue for you.

Thank you @WhiteAbeLincoln and @CGavrila!
