### ISSUE TITLE
0.12.2 npm install package error

### ISSUE THREAD

**Issue by NicholasXia** [joyent/node#16188]
tongshinjiedeiMac:8gegu tongshinjie$ npm install chalk --save
npm ERR! Darwin 13.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "chalk" "--save"
npm ERR! node v0.12.2
npm ERR! npm  v2.5.1
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module 'hosted-git-info'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tongshinjie/Desktop/8gegu/npm-debug.log

**Comment by misterdjules** [comment]
Thank you for creating this issue!

I could not reproduce this problem. It's also not clear it is a bug with node. Would you mind posting in the [Node.js Google group](https://groups.google.com/forum/#!forum/nodejs) and/or on Stack overflow first?

Closing this issue for now. If it turns out it's a problem with Node.js itself, we'll reopen it. Thank you!
