### ISSUE TITLE
Local Codepage support on Windows

### ISSUE THREAD

**Issue by be5invis** [joyent/node#2229]
As known, Windows Console defaultly uses local code page (e.g. in a Japanese system, it is 932). However Node defaultly expects utf-8.

I'm expecting Node to support codepages on Windows, including default codepage (can be get by `GetACP`, `"ConsoleEncoding"` for `setEncoding`) and specific codepage number (`"w32-cp936"`, for example).

**Comment by orangemocha** [comment]
@piscisaureus  did you have a chance to look into this?

**Comment by piscisaureus** [comment]
@orangemocha 

This issue itself isn't valid at this point (I'm not sure it ever was but it could be).
Node uses unicode APIs only to interact with the console; if text doesn't display properly in a console window that's because the user didn't pick the right font for their console window (so all the characters that that are not supported in the selected font show up as squares).

#2190 hasn't been solved though. At the time we decided that it wasn't worthwhile to add support for legacy encodings to node.js.

**Comment by jasnell** [comment]
Ok, given review that I'm going to close this issue. Feel free to reopen if necessary.
/cc @joyent/node-coreteam

**Comment by orangemocha** [comment]
Thanks for clarifying, @piscisaureus !
