### ISSUE TITLE
test/simple/test-tls-server-verify.js times out on our Windows 2012 Jenkins agent

### ISSUE THREAD

**Issue by misterdjules** [joyent/node#25279]
This currently prevents us from using the node-accept-pull-request job to land changes. I did some additional tests, and `test/simple/test-tls-server-verify.js` takes around 80 seconds to run on our Windows 2012 server Jenkins agent. It takes less time on my local Windows 7 VMWare VM (under 60 seconds).

@orangemocha Do you have some time to look into this?

**Comment by jbergstroem** [comment]
See https://github.com/iojs/io.js/issues/1461 for more info.

**Comment by misterdjules** [comment]
@jbergstroem Thank you for the heads up, very much appreciated :+1:

**Comment by orangemocha** [comment]
Investigating... we'll probably have to mark it as flaky to unblock the CI.

**Comment by orangemocha** [comment]
The test is slow on Windows because of two 1 second delays in the Windows version of openssl-cli.exe. We have reported the issue to openssl: http://rt.openssl.org/Ticket/Display.html?user=guest&pass=guest&id=3849

Now working on a workaround, modifying the test to let all those test cases run in parallel instead of serialized, so that it finishes quickly in spite of the openssl-cli delay.

**Comment by orangemocha** [comment]
PR ready: https://github.com/joyent/node/pull/25368

**Comment by orangemocha** [comment]
Fixed in https://github.com/joyent/node/commit/10349829f2f462e57cf7db2ef4c3a387d23e4826, which also unmarks the test as flaky.
