### ISSUE TITLE
Allow modifying the installed cert store

### ISSUE THREAD

**Issue by ubershmekel** [joyent/node#25507]
The certificates living in `https://github.com/joyent/node/blob/master/src/node_root_certs.h` doesn't allow removing or adding certificates by users. I'm trying to use `tsd` in a corporate environment and can't unless I compile node myself to modify that `.h` file or modify the installed `tsd` source to add my corp's MITM cert in the code.

I know @bnoordhuis is not sympathetic towards the coroporate MITM as stated here https://github.com/joyent/node/issues/6085 but this also impacts anyone who wants a smaller set of certs to be trusted for whatever project that requires extreme security measures. Having the certs live in an installed file sounds to me like a reasonable compromise.

Would a pull request like that be a good idea?

**Comment by sam-github** [comment]
Just because @bnoordhuis isn't going to do the work, doesn't mean it wouldn't be sucessful. node doesn't default to using the system CA store, but OpenSSL has APIs to do so, and I've been meaning for a while to try to add APIs to explicitly load CAs, and also to explicitly load them from the system.

I'd try to PR such things to nodejs/io.js if you have the energy, be prepared for lots of comment on the API and all, but it seems pretty useful to me.

**Comment by Perseid** [comment]
+1, lots of HTTP2 tools and libraries (e.g. https://www.npmjs.com/package/http2) require the use of TLS and testing without using your own custom testing certificates is really difficult or tedious.
Oh, and is there any reason this feature-request is not in the current node repository? (https://github.com/nodejs/node/issues?utf8=%E2%9C%93&q=Allow+modifying+the+installed+cert+store)
