### ISSUE TITLE
accessing `./file` in a required module

### ISSUE THREAD

**Issue by amir-s** [joyent/node#25508]
I'm not sure if this is an intended behaviour or not.

Assume this directory structure:

```
/home/amir
|-- file1.js
|-- folder
|   `-- file2.js
|   `-- file3.js
```

```
// file1.js
require('./folder/file2');
```

```
// file2.js
console.log( require('fs').existsSync('./file3.js') );
```
`file3` and `file2` are in the same folder, so it should print `true`, but it prints `false` when I execute `node file1.js` from `/home/amir`.

If I execute either `node file2.js` or `node ../file1.js` from `/home/amir/folder` it prints `true`.

**Comment by amir-s** [comment]
I guess one should use `__dirname` and resolve the path to do this kind of thing, am I right?

**Comment by sam-github** [comment]
That's one way. `./` means *very* different things in a `require()` statement, and the `fs` module. In fs, `.` refers to the current working directory, in `require`, it refers to relative to the file doing the require.

Btw, you can also do `require.resolve()` instead of using `__dirname` in many circumstances, take a look at its docs.
