### ISSUE TITLE
Help Post and nodejs

### ISSUE THREAD

**Issue by thiagoanselmo** [joyent/node#25543]
Good afternoon ,

I am studying There nodejs . I'm doing hum logon form with post method , So That When sending Gives Error

"Can not Post / ENTER "

I am using

var = expressed require (' express' )
Cargo = require (' express -load " )
, BodyParser = require (' body -parser " )
, Expressed app = ();

app.set ( ' views ' , __dirname +' / views ");
app.set (" display engine ',' SYS ');

app.use ( bodyParser.json ( ) ) ;
app.use ( bodyParser.urlencoded ( { extended : true } ) ) ;
app.use ( express.static (__ dirname + ' / public '));

load ( "models" )
.then ( ' Drivers ' )
.Then (" Routes" )
.into (app) ;

app.listen (3000 , function () {
console.log ( " Running . ");
} ) ;

**Comment by misterdjules** [comment]
It doesn't seem, at least for now, that it's an issue with Node.js' core. Please use the [Node.js Google group](https://groups.google.com/forum/#!forum/nodejs) or [StackOverflow](http://stackoverflow.com/questions/tagged/node.js) to ask this question.

If it turns out to be a bug in Node.js itself, then please add a comment here to reopen the issue and provide the information mentioned here: https://nodejs.org/contribute/#index_md_reporting_an_issue.

Thank you!
