### ISSUE TITLE
Adding a "mentor-available" label

### ISSUE THREAD

**Issue by misterdjules** [joyent/node#25618]
In trying to find ways to not block anyone from contributing and fixing important issues and bugs in node, I realized that some users of node are able and interested in contributing but lack a mentor to guide them through some of the hoops of getting a PR merged in the code base. I think this is true for people who have never contributed, but also for existing contributors.

This is definitely not new. Some contributors tried to address this problem and came with interesting solutions. For instance, the "easy" label was added to this issues tracker. Node forward had started a [mentors repository](https://github.com/node-forward/mentors). I'm sure there has been other initiatives.

I don't think the "easy" label led to any significant improvement. Part of this could be because new contributors are not necessarily interested in solving only easy issues. There is a broad range of issues and almost everyone is interested in different areas and complexity levels. There is also not really one such thing as an "easy" issue when it comes to contributing to node, as even the slightest change can have a huge impact and needs a lot of thought.

I haven't participated in [node forward's mentors program](https://github.com/node-forward/mentors). It seems to have stopped as he latest PR was created in January 2015, but it would be interesting to get feedback from participants. Maybe @jasonrhodes has some interesting insights to share? Anyway, it seems that such a program would benefit from having some metadata in the issues tracker itself that identifies which issues have at least one mentor available.

Having a "mentor-available" label would allow anyone interested in contributing to quickly filter issues for which a mentor is available. They could contact the mentor(s) and be confident that they will be able to move things forward. My hope is that it would encourage people interested in contributing to actually start doing it more. This could lead to more permanent collaborators added to the project, but it doesn't have to go this far to be successful.

Mentoring would be completely opt-in, that is a collaborator would be able to add the "mentor-available" label and mention in comments how to reach him/her. Mentors would be required to be available on GitHub and a more real-time discussion system (probably IRC) enough to not block anyone. If not available anymore, they could just remove the label or find another mentor and mention it in the comments.

We would be able to advertise issues for which a mentor is available on the website, and on any other medium that the evangelism group would find suitable. 

I have already a long list of issues for which I would be available as a mentor, here's a sample list quickly put together by skimming through issues: https://github.com/joyent/node/issues/8676, https://github.com/joyent/node/issues/8877, https://github.com/joyent/node/issues/17202, https://github.com/joyent/node/issues/14171, https://github.com/joyent/node/issues/6070 and https://github.com/nodejs/io.js/issues/583. I actually added the "mentor-available" label to https://github.com/joyent/node/issues/8676 so that you can see how it would work, see https://github.com/joyent/node/issues/8676#issuecomment-118144243.

I have the feeling that most current collaborators would also be able to mentor contributors to work on many other issues.

@joyent/node-collaborators Thoughts?

**Comment by whitlockjc** [comment]
As someone new to Node.js contribution, I think this is a great idea.  I had no idea other initiatives had been started so if you continue using them, it might make sense to bring those to the forefront so new people find those existing things easier.  *(This could be due to me not reading the right thing of course so my not knowing of the other initiatives it not necessarily indicative of some communication issue, just a possibility.)*  I like the idea proposed by @misterdjules because it would be very clear when looking at the issue tracker even with little documentation.  It will also give the potential contributor someone tangible to reach out to when looking into or working on the issue.

One thing to be careful of is to make sure when documenting this we mention that mentoring an issue does not give the interested community members a red phone that gives immediate, direct access to the mentor.  Mentors already have enough on their plate so expecting that the mentor will immediately and always be available is not fair.  But there should also be some level of quickness in requests for information from the potential contributor.

My last concern is the time it might take to ensure this works.  Since mentorship is opt-in, committers would need to be watching the issue tracker so that they can triage these things.  I'm sure this is already happening but this will be yet another thing to do...

**Comment by tyleranton** [comment]
+1

I like this idea a lot. I'm new to node and often find it troublesome finding an issue I feel comfortable with taking on. This would make it feel less daunting, and more friendly to new contributors.

**Comment by misterdjules** [comment]
Node.js' TSC agreed to use that label during [our latest meeting](https://github.com/nodejs/node/issues/64), so closing this issue.

@joyent/node-collaborators If you're interested in mentoring people for any issue/PR, please add the `mentor-available` label on these issues and add a comment indicating your contact info [like I did on some issues already](https://github.com/joyent/node/issues/8676#issuecomment-118144243).

Remember that it's opt-in, no obligation and you can dedicate the time you want to it.
