### ISSUE TITLE
test: test-http-dns-fail should be made non-flaky

### ISSUE THREAD

**Issue by joaocgreis** [joyent/node#25673]
simple/test-http-dns-fail is currently marked as flaky on Solaris. It should be investigated and made non-flaky.

Quick command for testing:
```
time (OK=0; NOK=0; for i in `seq 10000`; do ./out/Release/node test/internet/test-http-dns-fail.js && OK=$(($OK+1)) || NOK=$(($NOK+1)); echo "$i   OK: $OK   NOT OK: $NOK"; done)
```

Links:
- File: https://github.com/joyent/node/blob/b8ac6584faf00f6bc9302913ea58e54dcf8f559c/test/internet/test-http-dns-fail.js
- File history: https://github.com/joyent/node/commits/b8ac6584faf00f6bc9302913ea58e54dcf8f559c/test/internet/test-http-dns-fail.js
- Marked flaky on: [Nov 7, 2014](https://github.com/joyent/node/commit/0674cbaceb81ba1130355aa7eb8e6389824e3cc4) 

/cc @joyent/node-collaborators

**Comment by joaocgreis** [comment]
I cannot see this test fail on SmartOS x86 with the current v0.12. More results would be welcome.

**Comment by misterdjules** [comment]
@joaocgreis Thanks for creating this issue. I had created https://github.com/joyent/node/issues/8056 a while ago about the same problem, let me check if our SmartOS Jenkins node have actually been switched to Google DNS.

**Comment by misterdjules** [comment]
@joaocgreis The DNS configuration has indeed been changed to use DNS servers [as mentioned in that issue](https://github.com/joyent/node/issues/8056#issuecomment-70268526) a few months after the test was marked flaky. If you weren't able to reproduce this failure, I would just remove the test from the flaky list.

**Comment by joaocgreis** [comment]
@misterdjules Thanks! I'm preparing a PR, I will include this.

**Comment by joaocgreis** [comment]
@misterdjules For `test-dns` you marked https://github.com/joyent/node/issues/9034 as a duplicate of the issue you mentioned above. I cannot get it to fail on Linux, Windows or SmartOS. Can I assume it was also fixed by the DNS configuration?

**Comment by misterdjules** [comment]
@joaocgreis Yes, it is fair to assume this was fixed by the DNS configuration. You could even change the DNS configuration on the SmartOS agents to point to 209.244.0.3 (the level3 DNS server mentioned in [my original description of the problem](https://github.com/joyent/node/issues/8056#issue-39333434)) in addition to 8.8.8.8 and see if you can reproduce the problem, but I would not bother.

The worst thing that  can happen is that the test will fail again at some point, and we'll add it to the flaky list again, and start the investigation from where we left it now.

**Comment by joaocgreis** [comment]
Unmarked flaky in 78d256e7f5def6e1ffbf5fb5b232ecf78bc7bde5.
