### ISSUE TITLE
setInterval Crash with long delay interval

### ISSUE THREAD

**Issue by gdoron** [joyent/node#25761]
All the details are in this [Stackoverflow question](http://stackoverflow.com/q/31596926/601179).
Just note that giving a simple reproduce-able code isn't trivial and we didn't manage to do so as the code breaks only inside our project, when it's isolated it doesn't crash.

**Comment by Fishrock123** [comment]
@gdoron Your stackoverflow question does not produce any issue in either way; however, your ex-boss's does.

The reason for it not working is due to scope. Something within the original function was not available because when called from a timeout, it is called from the timeout's scope.

When you add an extra closure (a function) it gets called with the timeout's scope, but the function you are trying to call is able to reference the local scope outside of the timeout.

If you want an example, I accidentally ran into this just earlier: https://github.com/nodejs/io.js/pull/2231#discussion_r35350052

This is really just a nuance of javascript. Annoying at times, useful at others. There should be plny of articles about it :)

**Comment by thefourtheye** [comment]
@Fishrock123 But then the ex-boss's shouldn't be failing, right?

@gdoron I see that you tagged windows in the question, is this reproducible only in Windows?

**Comment by gdoron** [comment]
@thefourtheye, I can't say about other OSes as he has only windows.

@Fishrock123, I didn't understand your answer, that func function has only one line in it off console.log how scope related here? Specially that it breaks only with long delay interval.

**Comment by Fishrock123** [comment]
Investigating. It looks like v8 GC'd it early. (Which I'm guessing is a 0.12.4 v8 bug?)

Basically what's happening is that the callback is disappearing, assuming that it's not a user bug.

I wasn't able to reproduce it by forcing the gc (`--expose_gc` && `gc();`) on io.js 2.4.0, so I'm trying to make it run the full time, will check 0.12 after if I can't reproduce.

**Comment by Fishrock123** [comment]
I can't reproduce this on 0.12.4. I don't know of any GC bugs, and long timers work for me, and I don't know of any other failures we've had with them, so I have to conclude that your ex-boss must have messed up his function scoping. :s

> I didn't understand your answer, that func function has only one line in it of console.log how is scope related here? Specially that it breaks only with long delay interval.

Again, it would probably be best to read up on function scope in javascript and callbacks.

The extra function pulls whatever your boss was doing back into scope. (He can't have just been doing `console.log()`, because as you say, that does not break, which is as it should be.) :)

**Comment by jasnell** [comment]
I'm unable to reproduce either. Going to close unless it can be reliably reproduced. If it can, we can reopen.
