### ISSUE TITLE
Not able to install node js in Windows 10

### ISSUE THREAD

**Issue by msvkrishna** [joyent/node#25982]
It is showing 2502/2503 error.

Tried with admin privileges but still not working

![image](https://cloud.githubusercontent.com/assets/18426509/14579913/14285216-03d9-11e6-81ac-9008f2eb6abc.png)

**Comment by msvkrishna** [comment]
Any sugesstions

**Comment by atomic1fire** [comment]
you posted in the archive for node.js 0.0. Meaning that it hasn't actually been maintained since 2015.

Are you sure you're using a stable version of [nodejs](https://nodejs.org/en/)? If so you should probably file an issue [here](https://github.com/nodejs/node/issues)

Otherwise I'd still suggest recreating the post at the current github page because it will give your issue more attention.

**Comment by orangemocha** [comment]
@msvkrishna can you please report this in https://github.com/nodejs/node  and provide more information on which version of Node you are trying to install? Thanks!
