### ISSUE TITLE
Detecting the differences between an intended close and an unintended close

### ISSUE THREAD

**Issue by 3rd-Eden** [joyent/node#4739]
When you connect to a server using `TCP` connection you cannot detect or figure out how, or from what side the connection was closed. 

My main case here is for a fail over solution, when the server has closed the connection I need to attempt a (new or the same) connection again. But when I or a other user closes the connection manually using a `end/destroy` call, we don't want to do this behaviour. 

My only solution for this is to override `end/destroy` calls, capture the stack trace and see if it was called in node's modules or by user.

**Comment by misterdjules** [comment]
I just found out about this issue when doing some triaging of older issues.

It also seems to me that this would be better solved by adding some logic to your module. However, it's difficult to tell exactly without some code that represents what you're trying to do.

Since the time this issue was created, did you find a way to get what you were looking for without changing node's core?

**Comment by misterdjules** [comment]
Closing for lack of feedback. Please feel free to add comments if you feel strongly about this issue.
