### ISSUE TITLE
eval in the repl hangs on incomplete expressions

### ISSUE THREAD

**Issue by sam-github** [joyent/node#6922]
This is correct, the function call is incomplete:
```
% node -e 'eval("console.log(")'

undefined:1
console.log(
            
SyntaxError: Unexpected end of input
```

But at the REPL:

```
% node
> eval("console.log(")
... 
... ;
... 
...
```
The only way out is to kill the REPL, as far as I can tell.

The REPL seems to think the eval will or can be continued, that doesn't seem right, perhaps this is a side-effect of an implementation detail?

**Comment by misterdjules** [comment]
There seems to be a more general issue with node v0.10.x's REPL. For instance:
```
➜  v0.10 git:(v0.10) ✗ ./node
> process.versions
{ http_parser: '1.0',
  node: '0.10.37-pre',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.30',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1l' }
> var h = eval("function (a, b) { return a + b; }")
... foo
... bar
... ;
... .clear
> %                                                                                                                                                                                                                                                                           ➜  v0.10 git:(v0.10) ✗ ./node -e 'eval("function (a, b) { return a + b; }");'

undefined:1
function (a, b) { return a + b; }
         ^
SyntaxError: Unexpected token (
    at [eval]:1:1
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at startup (node.js:80:7)
    at node.js:929:3
➜  v0.10 git:(v0.10) ✗
```

In the example above, we can see that even though a `SyntaxError` is thrown when V8 parses the code that is executed via the REPL, the REPL just swallows the error thinking that it might be recoverable by adding more tokens.

The REPL's `.clear` command can still be used, but it's less than ideal since it doesn't output the proper error message, and makes diagnosing the issue difficult.

In v0.12, what happens is that the REPL [first compile the code to check for syntax errors](https://github.com/joyent/node/blob/v0.12/lib/repl.js#L115-L127). If there is no syntax error, [the REPL executes the code](https://github.com/joyent/node/blob/v0.12/lib/repl.js#L129-L145). Syntax errors are "swallowed" only at the time when the syntax is checked, not when the code is executed.

This is an important distinction since the syntax for the code executed by `eval` will only be checked by V8 when the code is actually executed, not during the previous syntax checking step (the code is only compiled). As a result, syntax errors in `eval` arguments are outputted as expected by node v0.11.x and node v0.12.x.

I would suggest to rename and change this issue's description to describe this more general problem, and to try to fix it by adopting the two-steps process that is used in node v0.12.x's REPL to check for syntax errors and execute code.

What do you think?

**Comment by sam-github** [comment]
IMO, if this is fixed in 0.12, it should be closed in 0.10. The time is better spent on improving the latest stable releases.

**Comment by misterdjules** [comment]
@sam-github That makes sense, thanks!

**Comment by sam-github** [comment]
No problem, thanks for all the issue cleanup.
