### ISSUE TITLE
add --full_path_breakpoint for debugger

### ISSUE THREAD

**Issue by timoshiu** [joyent/node#7315]
When "node debug" stop at file:line, it print out
1. break in <file_name:line_number>
2. <list of content at that line, along with 2 lines before and after each)
3. debug>

Can I add a debug specific flag, like "node debug --full_path_breakpoint",
so that we see the full path, absolute from the root, of the <file_name:line_number>
in item 1. above?
 
Also, need to preserve the full path when node/lib/*js is put together. so the 
"node debug" will also show where are the source code are. for example.
if we break into a line in module.js, it will print the full path or absolution path
/whatever/it/was/to/node/lib/module.js.

**Comment by fakedrake** [comment]
What is the status of this request?

**Comment by rocky** [comment]
timoshiu:
> In my fork, I have add a flag --debug-with-gud, 

indutny:
>There is something that bothers me about it, but I'm not sure what it is yet..

I was looking at this in more detail and here's my thoughts. The name `--debug-with-gud` is a highly-specific name that can cover a lot of things. 

The aspect that is problematic has to do with the terminal escape sequences that are added. There already is a REPL option *useColors* which can be disabled via environment variable `NODE_DISABLE_COLORS`. However there are a few more escape sequences that aren't handled. Specifically, those around prompting. 

And that brings up another point, that this isn't so much about using colors as it is about using escape sequences, and/or terminals because bolding and underlining, and italicizing aren't strictly colors.

**Comment by jasnell** [comment]
@timoshiu ... is this still something you'd like to pursue?

**Comment by jasnell** [comment]
Closing this here for now. If this is something that anyone would like to pursue further, opening a new PR against master in nodejs/node would be the right approach.
