### ISSUE TITLE
NodeJS Windows MSI installs Per User

### ISSUE THREAD

**Issue by chrpai** [joyent/node#7629]
The node-v0.10.28-x86.msi does not have the ALLUSERS property defined in the property table and doesn't have a UI option for selecting per-user / per-machine.  This means by default it installs as per-user.  The resources are installed in per-machine locations though.   This creates servicing problems in that only the person who originally did the install can uninstall it.  I discovered this when I was creating an installer and I wanted to use the Upgrade table to detect the NodeJS install and block installation if it wasn't present.  Since another developer did the NodeJS install my MSI couldn't find the NodeJS installed product.   The following code should be added to the WiX source:

(tag) Property Id="ALLUSERS" Value="1" (endtag)

On a side note, it's not possible to perform a major upgrade and switch installation context.  Deployed versions of NodeJS will have to be first uninstalled.

**Comment by joaocgreis** [comment]
Fixed by 8e80528453aca0354422162e09c7c9f4700ddb1e. Thank you!

**Comment by heifer1981** [comment]
Hi all. I know this issue is closed and that Node has moved on significantly since this. Just to put things into context for this comment we use Meteor but to deploy easily onto Windows hardware we demeteorize our projects so it will run on node and node v 0.10.4 is the only version so far we have found this works for. I spent days trying to find why our WIX Uninstallation would not work and this thread let me to what it was. In my WIX package I force the per machine setting to yes and now the nodejs package uninstalls without error and without needing custom actions to perform this cleanup. 
Eg.             MsiPackage Id="NodeJSMSI"
                  DisplayName="Node JS Framework Installer"
                  Cache="yes"
                  Compressed="no"                  
                  Permanent="no"                  
                  Vital="yes"  
                  DisplayInternalUI="yes"
                  EnableFeatureSelection="yes"
                  ForcePerMachine="yes"
                  SourceFile=".\node-v0.10.40-x64.msi"                 

Hope this helps someone else trying to figure out why nodejs is breaking your uninstallation chain and the settings it requires to perform this operation automagically :)
