### ISSUE TITLE
major mdb_v8 update for 0.12 and later

### ISSUE THREAD

**Issue by davepacheco** [joyent/node#8718]
This issue describes some major mdb_v8 changes.  I've already done most of the work and testing for this.

Bugs fixed:
- v0.12 and later: in-object properties not printing correctly (the main motivation for this issue)
- 64-bit: not printing external strings correctly (offset was hardcoded for 32-bit).  You'd mainly see this in "::jsstack -vn0" because the script "node.js" wasn't printed correctly, at least with 0.10 core files.
- 64-bit: printing JS source (via "::jsstack -v") emits errors and shows the wrong code
- Fixes several build warnings
- Two-byte strings are unnecessarily truncated
- Could print friendlier note when given obviously bogus function token positions

New features:
- ::jsstack prints *much* cleaner output by default
- ::jsprint keys should be quoted
- ::jsstack -v includes "this" value for each function on the stack
- ::jsstack -v includes more details about each argument (constructor names for each object)
- new commands: ::jsconstructor, ::jsfunctions, ::jssource, ::nodebuffer, ::v8internal
- ::findjsobjects and ::jsprint hidden flags for developers to measure and improve test coverage
- internal jsobj_properties() function is much better documented

**Comment by misterdjules** [comment]
@davepacheco @tjfontaine If I understand correctly `mdb_v8.so` can be built for SmartOS separately and doesn't necessarily need to be in Node.js' codebase. This is currently scheduled for 0.12.1, could you please confirm that landing it in v0.12.0 is not critical? Basically, I want to confirm that it can be built for SmartOS out of band so that SmartOS users will be able to use mdb to debug core files generated by node v0.12.0 when it's released.

Regardless, I'd like to have a PR up for these changes soon. I know that last time I did test it, I used my [v0.12-mdb-update branch](https://github.com/misterdjules/node/commits/v0.12-mdb-update), which contains [one change that you might not have](https://github.com/misterdjules/node/commit/7003100e380dc425650b48e20a71c65ec71bceba) in your local branches.

The commits in that branch will also need to be squashed, and I'm not in the best position to do that since I don't have all the context regarding these changes. @tjfontaine @davepacheco Does any of you have some time to do that? is 0.12.1 a reasonable target?

Thank you!

**Comment by davepacheco** [comment]
I'd have much preferred to get this into v0.12.0.  Although the shared object is currently delivered with SmartOS, it really evolves in lockstep with Node, not the operating system.  It's extremely useful to know that the version of mdb_v8 that's bundled with Node X works with Node X.  It becomes a real mess to keep track of which versions of mdb_v8 were intended for which versions of Node if they don't match up.

Relatedly, and in answer to your second question, I would hate to ship Node 0.12 and then find that the dmod that we've currently got doesn't work on 0.12 for one reason or another.  We may find that there's additional metadata we want in V8 in order to make it work, but there will be no way to add that to 0.12 if we only discover the problem after we ship 0.12.

All that said, whatever we integrate into Node.js, we'll integrate into SmartOS as well (but we'll only do that when Node.js integrates the change).  The mdb_v8 files in each repository should remain identical except for the license header.  Many users will only use the version shipped with SmartOS, and many more can build it separately from their "node" binary using a different version of the repo.  In that sense, it doesn't matter, but for the reasons above, it would be much better to ship this with 0.12.0.

As for the PR and commits: I haven't touched this since you picked up the changes and added your commit.  I believe that commit was fully tested with 0.12 and 0.10, both 32-bit and 64-bit.  I'm not sure what's changed in master, so I can't say whether that testing should be redone.  I know TJ has more changes, and I don't know what they've been tested on.  If those changes break on 0.10 or 0.12, we could consider a middle approach of retesting the previous changes (which at least get the dmod working on 0.12) and integrating those into 0.12.0, and then delivering TJ's updates (which I believe are all new features) in 0.12.1?

**Comment by misterdjules** [comment]
@davepacheco Sounds good! The plan now is to have @tjfontaine and myself work on squashing the commits and test them again. Assuming all goes well, it will land asap in v0.12, before node v0.12.0 is released.

**Comment by davepacheco** [comment]
Thanks!  That sounds great.

**Comment by misterdjules** [comment]
@davepacheco Thank you! Fixed in 4312f8d760bdf574b5a461e426331f0b4d298f18, ebfa7e350aed8f61b68a290be2e8fefca9db939e and 878c40e1b3762a5f3ed48094f954fbee705f69ff.
