### ISSUE TITLE
http "HPE_INVALID_STATUS" issue

### ISSUE THREAD

**Issue by leonkaihao** [joyent/node#8760]
My company has a golang http server, 
it returns status code big than 301000 when response a error,
My Nodejs http module will treat it as a exception,
with code "HPE_INVALID_STATUS" and message "Parse Error".
And I can't get any header info from it, 
Pls give me some suggestion how to deal with it?

I need to get some information from the header to show error on my browser,
thanks!

**Comment by jasnell** [comment]
Does not appear to be an issue with node.

**Comment by jeroenvollenbrock** [comment]
I'm replying to this topic because of it high search-rank when you search for this error.
This error may also occur when you're passing an invalid status code with the HTTP response from within nodeJS without checking for a valid status code, for instance an object instead of a number (I've seen a lot of HTTP/1.1 [Object object] responses pass by when i was helping someone to debug this behaviour ...)
