### ISSUE TITLE
Node.js Setup Wizard ended Prematurely on Windows 7 32 bit

### ISSUE THREAD

**Issue by muni2explore** [joyent/node#9030]
Many of them posted same issue like this. I tried some of the solutions given, but none of them worked for me.

I had posted this issue stackoverflow in the following link.

http://stackoverflow.com/questions/27896355/node-js-setup-wizard-ended-prematurely-on-windows-7-32-bit

Here is my installer log file of this node.js

https://db.tt/223knP0A

Please provide quick solutions....

**Comment by misterdjules** [comment]
I answered [on stackoverflow](http://stackoverflow.com/questions/27896355/node-js-setup-wizard-ended-prematurely-on-windows-7-32-bit/28036526#28036526).

In the future, please do not cross-post issues from stackoverflow in node's core issue tracker, unless it can be demonstrated that it highlights an actual bug in node.

Closing the issue here, as the discussion should continue over in stackoverflow.
