### ISSUE TITLE
Upgrade npm to latest version

### ISSUE THREAD

**Issue by misterdjules** [joyent/node#9078]
@tjfontaine Creating this issue to keep track of it, did you have a specific version in mind?

**Comment by mzgol** [comment]
Node 0.11.15 included npm 2.1.6 instead of the latest stable 2.2.0. I'm hitting into some race conditions on 2.1.6 (see https://github.com/npm/npm/issues/6554) so I really hope you do update at least to 2.2.0 as I can't require all users of my packages to update npm.

**Comment by misterdjules** [comment]
Hi @othiym23! What version of npm would you suggest for node 0.11.16, knowing that hopefully this will be the latest release candidate before v0.12.0?

**Comment by othiym23** [comment]
@misterdjules I suggest [`npm@2.3.0`](https://github.com/npm/npm/blob/master/CHANGELOG.md#v230-2015-01-15) because it has a number of important bug fixes for windows, but doesn't have any of the incomplete features for the new npm registry (which makes it the least confusing release for people getting a newly-bundled version of Node). BTW, we are planning on releasing `npm@3` before the end of February, and I would, like, if the timing works out, to get that into 0.12. I'd really like to avoid going another substantial chunk of a Node release cycle with the bundled version lagging the released / supported version by a full major version.

I'm happy to put together a pull request for you, if you'd like. [Here's](https://github.com/iojs/io.js/pull/573) the most recent one I did for io.js.

**Comment by misterdjules** [comment]
@othiym23 A PR that upgrades npm to 2.3.0 would be great, thank you!

As for waiting for npm 3.0 before releasing node v0.12, it does not seem like it would be a good timing. We're pushing hard to release the latest release candidate, and adding more delay and uncertainty at this time in the process doesn't seem like a good idea to me.

**Comment by othiym23** [comment]
OK, I'll start putting together the PR now.

**Comment by misterdjules** [comment]
@mzgol I'm trying to make sure the issue mentioned in https://github.com/npm/npm/issues/6554#issue-46631287 is fixed with the upgrade to npm 2.3.0. I don't see where in your reproduction steps a second npm install is used, although the description mentions:
> I'm getting the ENOTEMPTY error in npm 2.1.5 on a second npm install after clearing a cache.

Could you please let me know when I should run npm install to reproduce this issue?

**Comment by mzgol** [comment]
> Could you please let me know when I should run npm install to reproduce this issue?

`npm install` is invoked by `npm test`; the module described does `npm install` when it detects that dependencies are out of date and the `install` option is set to `true`. Therefore, it's enough to follow the steps in the first post.

Look at https://ci.appveyor.com/project/mzgol/check-dependencies/build/job/p9u0tjdma96lnjkl; AppVeyor consistently fails on this module with Node 0.11.15 due to this issue.

**Comment by misterdjules** [comment]
@mzgol @othiym23 After upgrading v0.12 to npm 2.3.0 and [trying to reproduce @mzgol's issue](https://gist.github.com/misterdjules/6806904fd0422003852d) with a custom build on Windows, I get [the same error messages](https://gist.github.com/misterdjules/ec510a165ddb1b0ce291) as [what happens on AppVeyor with node v0.11.14](https://ci.appveyor.com/project/mzgol/check-dependencies/build/111/job/pwocdpwcpg3kc4ya).

The npm-debug.log file for the npm module that errors is available on [my Dropbox account](https://www.dropbox.com/s/2ak2hf6jek0pqb3/npm-debug.log?dl=0).

**Comment by mzgol** [comment]
@misterdjules Heh, you're right, I can even reproduce it with io.js 1.0.4 that has npm 2.3.0 included. I *used to* be able to reproduce it on OS X with older npm versions but cannot currently so I thought that's the same with Windows.

It seems it requires further debugging, seeing if the `fs-extra` package is doing something incorrectly or Node itself. Unfortunately, I'm not going to have time to look at it more closely this week; if no one else is reporting similar issues maybe it's not so important to hold a release.

**Comment by othiym23** [comment]
The bug on Windows may or may not be related to the bug on other operating systems. It seems likely that there is a race condition somewhere in the installation process, but it doesn't seem like npm itself is to blame, as it doesn't appear in the stacktrace in @misterdjules's `npm-debug.log`. Looking at that, the issue appears to be that a `node-modules` folder already exists when something else, probably a mkdir call, isn't expecting it to. If there's a race, that's likely to be where it's happening.

Windows is just thingy about directory access in a way that the Unices and OS X aren't. It looks like a stat call is going awry in [`mkdirp`](http://npm.im/mkdirp), and there's no special provision for handling that edge case in [`fstream`](http://npm.im/fstream). That, to me, says the issue is probably in either `mkdirp` or Windows itself, although it's possible it could be worked around in `fstream`. I'm happy to work with @mzgol on narrowing down his issue, but I don't think this should block the inclusion of `npm@2.3.0` in 0.11.16.

**Comment by mzgol** [comment]
> I'm happy to work with @mzgol on narrowing down his issue, but I don't think this should block the inclusion of npm@2.3.0 in 0.11.16.

I agree; thanks for looking into it!

**Comment by misterdjules** [comment]
Thank you @othiym23 and @mzgol, fixed by 491ac6a.
