### ISSUE TITLE
fs.existsSync is slow vs fs.openSync

### ISSUE THREAD

**Issue by shrewdlogarithm** [joyent/node#9128]
Note: not sure this is an issue as-such - rather a question which might turn into an issue

I've been hacking through an app I created, trying to remove bottlenecks and tidy code which won't optimize and I found something interesting 

fs.existsSync(filename) is quite slow - it also reports non-optimisable due to a try/catch?

The following code seems to do the same thing (and includes a try/catch so, again, won't optimize) but it runs at least twice-as-fast (in my test setup at least) - Node 0.10.35 on Windows

    try{
      var fd = fs.openSync(file)
      fd.close()
      // do whatever you did if fs.existsSync worked
    } catch(e) {
      // do whatever you did if existsSync failed
    }

I think this may be because fs.existsSync is doing a 'stat' - getting lots of info about a file which you might not actually need instead of just checking it exists???

Sorry if this is obvious/a given or I've misunderstood something - but certainly the latter code runs a LOT quicker for me...

**Comment by cjihrig** [comment]
With regards to performance, you should give `fs.access()` and `fs.accessSync()` a try if you are using the latest unstable branch. It works a lot like your `openSync()` example. However, it's worth pointing out that using `access()` and `exists()` is generally discouraged because it leads to race conditions in your code. If you're already using `open()`, you should probably stick with that.
