### ISSUE TITLE
shared stdio with child_process.fork

### ISSUE THREAD

**Issue by piranna** [joyent/node#9223]
When using child_process.fork, according to the docs it's the same as child_process.spawn, but use a new v8 isolate in the same process, starting faster and using less memory. Problem is that stdio is shared (maybe also other things?) Instead of doing a dup of the file descriptors, so when closing it on one of the process, get's closed for all of them.

**Comment by cjihrig** [comment]
> When using child_process.fork, according to the docs it's the same as child_process.spawn, but use a new v8 isolate in the same process, starting faster and using less memory.

The docs state otherwise:

> These child Nodes are still whole new instances of V8. Assume at least 30ms startup and 10mb memory for each new Node. That is, you cannot create many thousands of them.

Under the hood, [`fork()` is just calling `spawn()`](https://github.com/joyent/node/blob/v0.12/lib/child_process.js#L581). As for the stdio, the `silent` flag allows you to [either pipe or inherit](https://github.com/joyent/node/blob/v0.12/lib/child_process.js#L576-L577). If you need more fine grain control, you should use `spawn()` instead.

**Comment by piranna** [comment]
I know fork() is not free, but use less resources than creating a new process (speciall memory) since both process will share the same event queue and Node.js instance, problem is that they will share other things like stdio. I'm asking for this mostly for embebed devices, like in NodeOS.

**Comment by cjihrig** [comment]
As far as I know, `fork()` creates a whole new process.
