### ISSUE TITLE
unable to resolve dependencies in node 0.12.0 for private git repo urls with range specified version

### ISSUE THREAD

**Issue by ciekawy** [joyent/node#9416]
having dependency

```
  "dependencies": {
    "private-module": "git@prv.com:/path/module.git#^v1.2.3"
  }
```

there is an error 
```
npm ERR! Command failed: git rev-list -n1 %5Ev1.2.3
npm ERR! fatal: ambiguous argument '%5Ev1.2.3': unknown revision or path not in the working tree.
``` 
because of caret being url-escaped. This was working correctly with node 0.10.33 but not for 0.11.x and 0.12.0 so it looks like a regression bug.

**Comment by KenanY** [comment]
@ciekawy Erm, `npm` doesn't do any semver range resolution for `git` stuff. This has been requested many times before (https://github.com/npm/npm/issues/5826) but it would involve crawling tags in order to match them to the range.

**Comment by ciekawy** [comment]
I wonder what is the effect of using described semver on 0.10.33 then?
Maybe there should be then some message instead of silently providing
working result or failing - both are confusing.

W dniu poniedziałek, 16 marca 2015 Kenan Yildirim <notifications@github.com>
napisał(a):

**Comment by KenanY** [comment]
@ciekawy As far as I can tell, `npm` version is more important here than Node.js version.

**Comment by ciekawy** [comment]
I can confirm I have tried recent npm version in both cases and the
difference depends on node version

W dniu poniedziałek, 16 marca 2015 Kenan Yildirim <notifications@github.com>
napisał(a):

**Comment by ciekawy** [comment]
I was looking into the code and you're right - it seems like even if the provided semver is not causing an error it just does nothing (ie. the latest master revision is being checked out).

I was also checking the bower code and it looks quite interesting since there is complete implementation of resolvers (including GitResolver doing the semver stuff). I wonder if it would be good idea to try to extract this resolver as a module and then to use it in the npm?

**Comment by KenanY** [comment]
@ciekawy I'll defer judgement of that to @othiym23, the gatekeeper :)

previous mention of bower's resolver from last year: https://github.com/npm/npm/issues/3328#issuecomment-56892023

**Comment by othiym23** [comment]
The feedback various members of the npm team have gotten from many people involved in bower (not just users – some from contributors as well) is that applying semver-like meaning to git tags creates a nasty set of edge cases that are best avoided. Custom resolvers are also widely seen as a misstep – they make it so that dependency specifiers don't resolve to the same thing across projects, which is an ongoing (and somewhat unforgiving) cause of confusion.

A lot of time and effort has been putting into making everything work correctly with registries (not just the official one, either – the team does its best to ensure that npm continues to work with `sinopia`, `cnpmjs`, and other third-party (private) registries), and my position (if not the whole team's) is that GitHub dependencies are not the primary means for interacting with remotely stored packages, so it's OK if they don't have feature parity with packages hosted on a registry.

**Comment by misterdjules** [comment]
Closing as this is an issue with npm, not node.
